### ISSUE TITLE
path-to-regexp needs upgrade from 0.1.7 => 6.2.2

### ISSUE THREAD

**Issue by frank-dspeed** [frank-dspeed/express#1]
new named export because esModule true

Complet run 0.1.7 as reference what the expected results should look like: https://gist.github.com/frank-dspeed/26f65f34c15dafc1e097a15eedd83c22

see: [update_regex branch](https://github.com/frank-dspeed/express/tree/update_regex)
needs to get added in 

```
// packages/express/lib/router/layer.js
require('path-to-regexp').pathToRegexp

// packages/express/examples/downloads/index.js
L22: app.get('/files/:file(*)', function(req, res, next){
0.1.7: path:  /files/:file(*) regexp:  /^\/files\/(?:((.*)))\/?$/i
6.2.0: SyntaxError: Invalid regular expression: /^\/files(?:\/(*))[\/#\?]?$/: Nothing to repeat

// packages/express/test/Router.js
L348-363:  router.handle({ url: '*', method: 'GET' }, { end: cb }, no)
0.1.7:  path:  * regexp:  /^(.*)\/?$/i
6.2.0: TypeError: Unexpected MODIFIER at 0, expected END
```

Details First Error
```
SyntaxError: Invalid regular expression: /^\/files(?:\/(*))[\/#\?]?$/: Nothing to repeat
    at new RegExp (<anonymous>)
    at tokensToRegexp (express/node_modules/path-to-regexp/dist/index.js:390:12)
    at stringToRegexp (express/node_modules/path-to-regexp/dist/index.js:331:12)
    at pathToRegexp (express/node_modules/path-to-regexp/dist/index.js:405:12)
    at new Layer (express/lib/router/layer.js:47:19)
    at Function.route (express/lib/router/index.js:500:15)
    at Function.app.<computed> [as get] (express/lib/application.js:481:30)
    at Object.<anonymous> (express/examples/downloads/index.js:22:5)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (express/test/acceptance/downloads.js:2:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:331:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (express/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (express/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (express/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (express/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (express/node_modules/mocha/lib/cli/run.js:374:5)
{
  path: '/files/:file(*)',
  opts: { sensitive: false, strict: false, end: true },
  keys: [
    {
      name: 'file',
      prefix: '/',
      suffix: '',
      pattern: '*',
      modifier: ''
    }
  ]
}
```

Details Secund Error
```
TypeError: Unexpected MODIFIER at 0, expected END
    at mustConsume (express/node_modules/path-to-regexp/dist/index.js:114:15)
    at parse (express/node_modules/path-to-regexp/dist/index.js:173:9)
    at stringToRegexp (express/node_modules/path-to-regexp/dist/index.js:331:27)
    at pathToRegexp (express/node_modules/path-to-regexp/dist/index.js:405:12)
    at new Layer (express/lib/router/layer.js:47:19)
    at Function.route (express/lib/router/index.js:500:15)
    at Function.proto.<computed> [as all] (express/lib/router/index.js:515:22)
    at Context.<anonymous> (express/test/Router.js:356:14)
    at callFnAsync (express/node_modules/mocha/lib/runnable.js:394:21)
    at Test.Runnable.run (express/node_modules/mocha/lib/runnable.js:338:7)
    at Runner.runTest (express/node_modules/mocha/lib/runner.js:678:10)
    at express/node_modules/mocha/lib/runner.js:801:12
    at next (express/node_modules/mocha/lib/runner.js:593:14)
    at express/node_modules/mocha/lib/runner.js:603:7
    at next (express/node_modules/mocha/lib/runner.js:486:14)
    at Immediate._onImmediate (express/node_modules/mocha/lib/runner.js:571:5)
    at processImmediate (node:internal/timers:464:21)
{
  path: '*',
  opts: { sensitive: undefined, strict: undefined, end: true },
  keys: []
}
```

current translations

```
optional slash problem regexp does not want a trailing slash needs to get stripped before matching 
* gets (.*) 
: needs escaping when followed by expression \\:(\\d+) for example \\:()


```

relativ slash needs to get solved by packages/express/lib/router/layer.js line ~50 where also debug happens

**Comment by frank-dspeed** [comment]
looks like (*) needs to be .* and * needs to be .*

**Comment by frank-dspeed** [comment]
old behavior packages/express/test/app.router.js L324
```
path:  /user/id:(\d+)
regexp:  /^\/user\/id:(\d+)\/?(?=\/|$)/i
      ✔ should merge numeric indices req.params
```
current
```
path:  /user/id:numeric(\d+)
regexp:  /^\/user\/id(\d+)(?:[\/#\?](?=[]|$))?(?=[\/#\?]|[]|$)/i
```

**Comment by frank-dspeed** [comment]
try to fix trailing slash issue in Layer line 144~ and 55
in general all routes work as long as you do not register them with a trailing slash
